[project]
name = "careless-whisper-key"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pytz>=2025.2",
    "selenium>=4.38.0",
]
